name: oauth-jumpbox

instance_groups:
- name: oauth-jumpbox
  instances: 1
  azs: [z1]
  vm_type: default
  stemcell: default
  networks:
  - name: default
  update: {serial: true}
  jobs:
  - name: user_add
    release: os-conf
    properties:
      users:
      - name: jumpbox
        public_key: ((jumpbox_ssh.public_key))
  - name: dockersh
    release: oauth-jumpbox
    properties:
      env:
        BOSH_ENVIRONMENT: ((/concourse/main/bosh_environment))
        BOSH_CA_CERT: ((/concourse/main/bosh_ca_cert))
  - name: oauth
    release: oauth-jumpbox
    properties:
      pam_oauth:
        client-id: jumpbox
        client-secret: ((client_secret))
        redirect-url: "urn:ietf:wg:oauth:2.0:oob"
        scopes: ["openid"]
        endpoint-auth-url: "((/concourse/main/concourse_url)):8443/oauth/authorize"
        endpoint-token-url: "((/concourse/main/concourse_url)):8443/oauth/token"
        username-format: "%s"
  - name: ca_certs
    release: os-conf
    properties:
      certs: ((/concourse/main/bosh_ca_cert))
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

variables:
- name: jumpbox_ssh
  type: ssh
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth
- name: client_secret
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: os-conf
  sha1: f515406949ee0bba0329d1ce4a7eb1679521eabd
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=19
  version: 19
- name: docker
  sha1: 8836ed245406abea5eaa0b3aacb568ea421eb7b3
  url: https://github.com/cloudfoundry-incubator/docker-boshrelease/releases/download/v33.0.0/docker-33.0.0.tgz
  version: 33.0.0
- name: oauth-jumpbox
  sha1: 1e98e3394e06a3832388147552e617cd6fdfe554
  url: https://github.com/cloudfoundry-community/oauth-jumpbox-boshrelease/releases/download/v0.3.0/oauth-jumpbox-0.3.0.tgz
  version: 0.3.0
